mode: "dev" #dev 开发模式，日志打印到控制台，prod  生产模式，日志不打印控制台
port: 8088
datasource:
  master:
    driver_name: "mysql"
    host: "127.0.0.1"
    user: "root"
    password: "1234"
    dbname: "zdmin"
    port: 3306
    max_open_conns: 200
    max_idle_conns: 50


  slave:
    count: 0
    driver_name: "mysql"
    hosts: "127.0.0.1,127.0.0.1"
    users: "root,root"
    passwords: "123456,123456"
    dbnames: "baize,baize"
    ports: 3306,3306
    max_open_connss: 200,200
    max_idle_connss: 50,50